import './Collect'
import './Cart'

export * from '@/duxcmsOrder/components'
export * from './Spec'
export * from './GoodsSpec'
export * from './MallCate'
export * from './MallList'
export * from './MallCateQuick'
export * from './MallQuick'
